apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: SelvaTestCatalog
spec:
  type: service
  owner: admin
  lifecycle: experimental
  catalogVersionInfo:
    latest: 'true'
    entityName: SelvaTestCat
  projectInfo:
    projectName: ConcordWeb
    moduleName: WebUpdate
    informationAuthor: ''
    modality:
      - UL
    bodyParts: ''
    processingPurpose: ''
    protocol: ''
    algorithmType: ''
    packageType: ''
    supportedOs: ''
    sourceCodeLanguage: ''
    developmentStatus: ''
    linkToProject: >-
      [ [H:T(Total Segmentator VAF - Image Analysis Community - Confluence
      (vitalimages.com))H:L(https://github.com/trrakesh/backstage_new)] ]
  applicationInfo:
    linkAPI: >-
      [ [H:T(Total Segmentator - Software Requirements Specification - Image
      Analysis Community - Confluence
      (vitalimages.com))H:L(https://github.com/trrakesh/backstage_new)] ]
    inputImages: ''
    inputValues: ''
    outputImages: ''
    outputValues: ''
    limitations: ''
    algorithmDevelopmentCompany: ''
  productization:
    productizedApplication: ''
    function: ''
    productizedOwner: ''
    releaseNotes: >-
      [ [H:T(Release
      documentation)H:L(https://github.com/trrakesh/backstage_new)] ]
    knowIssues: ''
  evaluationInformation:
    evaluationResults: ''
    evaluationType: ''
    clinicalData: ''
  algorithmInformation:
    developmentPurpose: >-
      [ [H:T(GitHub - wasserth/TotalSegmentator: Tool for robust segmentation of
      >100 important anatomical structures in CT and MR
      images)H:L(https://github.com/trrakesh/backstage_new)] ]
    developmentStatus: ''
    algorithmDevelopmentCompany: ''
    personinCharge: ''
    collaborativeResearchPartner: ''
    existenceofExternalIP: ''
  technologyInformationforCMRE:
    fundingProject: ''
    group: ''
    TRL: ''
    projectStatus: ''
