apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: SelvaTestCatalog
spec:
  type: service
  owner: admin
  lifecycle: experimental
  projectInfo:
    projectName: NewConfluence - WIth UserMapping
    moduleName: Selva
    informationAuthor:
      - admin
    modality:
      - UL
    bodyParts: Cardiac
    processingPurpose: segmentation
    protocol: Contrast
    algorithmType: Classical
    packageType: Binary
    supportedOs: Windows
    sourceCodeLanguage: Python
    developmentStatus:
      - Development
    linkToProject: Link
  productization:
    productizedApplication: Application
    function: Function
    productizedOwner: Owner
    releaseNotes: Notes
    knowIssues: Issues
  evaluationInformation:
    evaluationResults: Results
    evaluationType: Evaluation
    clinicalData: Clinical
  algorithmInformation:
    developmentPurpose: Processing
    developmentStatus: Clinical Validation
    algorithmDevelopmentCompany: Quest
    personinCharge: Selva
    collaborativeResearchPartner: RTR
    existenceofExternalIP: 'No'
  technologyInformationforCMRE:
    fundingProject: Father
    group: IMAGE ANALYSIS
    TRL: TRL 5
    projectStatus: LEGACY
  applicationInfo:
    linkAPI: test
